### ISSUE TITLE
Missing requirement: No module named 'gitdb'

### ISSUE THREAD

**Issue by pranasziaukas** [Michael-F-Bryan/auto-changelog#27]
The latest version of `gitpython` dependency drops sub-dependencies on `ddt`and `gitdb`.

```
  - Updating gitpython (2.1.12 -> 2.1.13)
  - Removing ddt (1.2.1)
  - Removing gitdb (0.6.4)
```

However, your package imports `gitdb` directly and, as a consequence, fails.

```
Traceback (most recent call last):
  File ".../lib/python3.7/site-packages/git/__init__.py", line 25, in _init_externals
    import gitdb
ModuleNotFoundError: No module named 'gitdb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../bin/auto-changelog", line 6, in <module>
    from auto_changelog.__main__ import main
  File ".../lib/python3.7/site-packages/auto_changelog/__main__.py", line 26, in <module>
    from .parser import group_commits, traverse
  File ".../lib/python3.7/site-packages/auto_changelog/parser.py", line 7, in <module>
    import git
  File ".../lib/python3.7/site-packages/git/__init__.py", line 33, in <module>
    _init_externals()
  File ".../lib/python3.7/site-packages/git/__init__.py", line 27, in _init_externals
    raise ImportError("'gitdb' could not be found in your PYTHONPATH")
ImportError: 'gitdb' could not be found in your PYTHONPATH
```

**Comment by KeNaCo** [comment]
Sorry for the missing comment. I'm going to resolve this during the weekend.

**Comment by KeNaCo** [comment]
So, `parser.py` was removed by #25. But for sure I updated requirements and tests pass.
