### ISSUE TITLE
not working in sub-folder

### ISSUE THREAD

**Issue by michaelaye** [Michael-F-Bryan/auto-changelog#44]
I have an unsual project layout of the github repo:

* heat1d
  * matlab
  * c
  * python
    * setup.py
    * heat1d/

and when i run auto-changelog inside the python folder i get:

```
$ auto-changelog --starting-commit 98f8a7d2a8285f0bce5ba67815f07da8924227f1
Traceback (most recent call last):
  File "/Users/klay6683/miniconda3/envs/py37/bin/auto-changelog", line 10, in <module>
    sys.exit(main())
  File "/Users/klay6683/miniconda3/envs/py37/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/klay6683/miniconda3/envs/py37/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/klay6683/miniconda3/envs/py37/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/klay6683/miniconda3/envs/py37/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/klay6683/miniconda3/envs/py37/lib/python3.7/site-packages/auto_changelog/__main__.py", line 56, in main
    repository = GitRepository(repo, latest_version=latest_version, skip_unreleased=not unreleased)
  File "/Users/klay6683/miniconda3/envs/py37/lib/python3.7/site-packages/auto_changelog/repository.py", line 14, in __init__
    self.repository = Repo(repository_path)
  File "/Users/klay6683/miniconda3/envs/py37/lib/python3.7/site-packages/git/repo/base.py", line 183, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /Users/klay6683/Dropbox/src/heat1d/python
```

can it be made so that it works inside the `python` subfolder and only creates a CHANGELOG.md there?

**Comment by michaelaye** [comment]
ah, it seems all i need to do is to use `--repo ..` ?

**Comment by KeNaCo** [comment]
Hi.
`--repo` is for setting which remote you want to use in issue links. For example, I have a fork of auto-changelog as my origin, which is the default. But want to use `--repo=upstream` for links.

But this looks like it does not discover .git in the path or parent paths. Where are your .git placed?

**Comment by michaelaye** [comment]
the `.git` folder is in `heat1d`, one directory higher than the `python` folder.

**Comment by KeNaCo** [comment]
Sorry for the late answer. I have time for OS only during the weekend and even then the family is first priority :)

I have some planned OS work for this weeken, so I will look at it.
