### ISSUE TITLE
TypeError: PackingType of packed-Refs not understood

### ISSUE THREAD

**Issue by masonlouchart** [Michael-F-Bryan/auto-changelog#6]
I got this error when I try to run the command `auto-changelog`:

> TypeError: PackingType of packed-Refs not understood: '# pack-refs with: peeled fully-peeled sorted'

The fact is, the plugin already worked on this project. Moreover, I have another project with same versions of _Python_, _Git_ and _auto-changelog_ and it works.

I don't understand the "packed-refs" things. I guess it's something from Git. The repo was deleted, the virtualenv completly uninstalled/reinstalled and the repo cloned again.

I got the same error. So it was not local durty Git refs...
I opened an issue here because didn't found anything anywhere else.

__Full Stacktrace:__

> Traceback (most recent call last):
  File "/Users/mason/.pyenv/versions/my-project/bin/auto-changelog", line 11, in <module>
    sys.exit(main())
  File "/Users/mason/.pyenv/versions/2.7.14/envs/my-project/lib/python2.7/site-packages/auto_changelog/__main__.py", line 46, in main
    tags, unreleased = traverse(args['--repo'])
  File "/Users/mason/.pyenv/versions/2.7.14/envs/my-project/lib/python2.7/site-packages/auto_changelog/parser.py", line 42, in traverse
    tags = repo.tags
  File "/Users/mason/.pyenv/versions/2.7.14/envs/my-project/lib/python2.7/site-packages/git/repo/base.py", line 352, in tags
    return TagReference.list_items(self)
  File "/Users/mason/.pyenv/versions/2.7.14/envs/my-project/lib/python2.7/site-packages/git/util.py", line 942, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
  File "/Users/mason/.pyenv/versions/2.7.14/envs/my-project/lib/python2.7/site-packages/git/refs/symbolic.py", line 609, in _iter_items
    for sha, rela_path in cls._iter_packed_refs(repo):  # @UnusedVariable
  File "/Users/mason/.pyenv/versions/2.7.14/envs/my-project/lib/python2.7/site-packages/git/refs/symbolic.py", line 100, in _iter_packed_refs
    raise TypeError("PackingType of packed-Refs not understood: %r" % line)
TypeError: PackingType of packed-Refs not understood: '# pack-refs with: peeled fully-peeled sorted'

Do you have any idea?

**Comment by masonlouchart** [comment]
I forgot to say I ran these commands before uninstall/reinstall everything:

```sh
git reflog expire --expire-unreachable=now --all
git gc --prune=now
```
