### ISSUE TITLE
Error on second run when no remote is defined

### ISSUE THREAD

**Issue by Celeborn2BeAlive** [Michael-F-Bryan/auto-changelog#74]
I created a project with no remote repository, with a first version tag "v0.1.0" and ran `auto-changelog --tag-prefix=v` to generate the `CHANGELOG.md` file. It worked fine and just warns me with:
```
ERROR:root:Remote named 'origin' didn't exist. Turning off issue links.
ERROR:root:Remote named 'origin' didn't exist. Turning off compare url links.
```

After a few commits, I add a new version tag "v0.2.0" but when I run the command again to update the changelog I get the following trace:
```
ERROR:root:Remote named 'origin' didn't exist. Turning off issue links.
ERROR:root:Remote named 'origin' didn't exist. Turning off compare url links.
Traceback (most recent call last):
  File "C:\Users\laure\.pyenv\pyenv-win\versions\3.7.6-amd64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\laure\.pyenv\pyenv-win\versions\3.7.6-amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\projects\c2ba_sandbox\my_addon\.venv\Scripts\auto-changelog.exe\__main__.py", line 9, in <module>
  File "d:\projects\c2ba_sandbox\my_addon\.venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "d:\projects\c2ba_sandbox\my_addon\.venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\projects\c2ba_sandbox\my_addon\.venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\projects\c2ba_sandbox\my_addon\.venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\projects\c2ba_sandbox\my_addon\.venv\lib\site-packages\auto_changelog\__main__.py", line 89, in main
    stopping_commit=stopping_commit,
  File "d:\projects\c2ba_sandbox\my_addon\.venv\lib\site-packages\auto_changelog\__init__.py", line 10, in generate_changelog
    changelog = repository.generate_changelog(*args, **kwargs)
  File "d:\projects\c2ba_sandbox\my_addon\.venv\lib\site-packages\auto_changelog\repository.py", line 79, in generate_changelog
    releases[release_index].set_compare_url(diff_url, releases[release_index + 1].title)
  File "d:\projects\c2ba_sandbox\my_addon\.venv\lib\site-packages\auto_changelog\domain_model.py", line 157, in set_compare_url
    self.diff_url = diff_url.format(previous=previous_tag, current=self.tag)
AttributeError: 'NoneType' object has no attribute 'format'
```
So it seems the second time the "turning off ***" does not work.

It is probably a minor issue since the common use case is to have a remote repository. If I had one everything works fine.

**Comment by KeNaCo** [comment]
Released in 0.5.1 :confetti_ball: 

Thank you for your report.
